version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  build-and-test:
    docker:
      - image: python:3.12
    steps:
      - checkout
      - run:
          name: install packages
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linting
          command: flake8

  containerize:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Containerize
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            docker build -t tortique/img_docker:$CIRCLE_SHA1 .
            docker push tortique/img_docker:$CIRCLE_SHA1

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings-ad web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-ad web

  deploy-render:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
    name: "Deploy"
    command: curl -X GET https://api.render.com/deploy/srv-cl683thk857s73cph6ug?key=wviVrZ_IoRs

workflows:
  main-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - containerize:
          requires:
            - build-and-test
        filters:
          branches:
            only: master
      - deploy:
          requires:
            - containerize
          filters:
            branches:
              only: master
      - deploy-render:
          requires:
            - deploy
          filters:
            branches:
              only: master